### ISSUE TITLE
Error occurs when running on Alpine Linux v3.8

### ISSUE THREAD

**Issue by gazf** [mahnunchik/gulp-responsive#107]
Please update the sharp version.

package.json
```
"sharp": "^0.21.0"
```

When installing to the new Alpine Linux, if the sharp version is old, an error will occur at run time.
```
internal/modules/cjs/loader.js:736
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
```

**Comment by aslafy-z** [comment]
Need to merge https://github.com/mahnunchik/gulp-responsive/pull/105

As a workaround, you can use the `greenkeeper/sharp-0.21.0` update branch in your `package.json` file :
```json
"gulp-responsive": "mahnunchik/gulp-responsive#greenkeeper/sharp-0.21.0",
```

**Comment by gazf** [comment]
@aslafy-z Thanks for the advice!
