### ISSUE TITLE
npm install error - node v14.17.6

### ISSUE THREAD

**Issue by crowscript** [mahnunchik/gulp-responsive#154]
I got this error:
```npm ERR! code 1
npm ERR! path C:\Users\crow\Documents\crow\www\VUE\Static\node_modules\gulp-responsive\node_modules\sharp
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
npm ERR! info sharp Using cached C:\Users\crow\AppData\Local\npm-cache\_libvips\libvips-8.8.1-win32-x64.tar.gz
npm ERR! info sharp Creating C:\Users\crow\Documents\crow\www\VUE\Static\FINAL\New folder (2)\node_modules\gulp-responsive\node_modules\sharp\build\Release
npm ERR! info sharp Copying DLLs from C:\Users\crow\Documents\crow\www\VUE\Static\node_modules\gulp-responsive\node_modules\sharp\vendor\lib to C:\Users\crow\Documents\crow\www\VUE\Static\FINAL\New folder (2)\node_modules\gulp-responsive\node_modules\sharp\build\Release
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.17.6 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\crow\Documents\crow\www\VUE\Static\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\crow\Documents\crow\www\VUE\Static\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\crow\Documents\crow\www\VUE\Static\node_modules\graceful-fs\polyfills.js:299:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\crow\\Documents\\crow\\www\\VUE\\Static\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\crow\Documents\crow\www\VUE\Static\node_modules\gulp-responsive\node_modules\sharp
npm ERR! gyp ERR! node -v v14.17.6
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
```

**Comment by steakpinball** [comment]
Do you have python installed?

**Comment by crowscript** [comment]
Oh, actually, no. I don't have :-/

**Comment by crowscript** [comment]
Yeah, that was the problem, thanks a lot!
