### ISSUE TITLE
Error on Install: node-gyp rebuild

### ISSUE THREAD

**Issue by jhough10** [mahnunchik/gulp-responsive#20]
Getting an error when trying to install into a new project.

```
$ npm install --save-dev gulp-responsive
 
> sharp@0.11.3 install /PROJECT_PATH/node_modules/gulp-responsive/node_modules/sharp
> node-gyp rebuild

Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
gyp: Call to 'PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10:$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig" pkg-config --libs vips' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /PROJECT_PATH/node_modules/gulp-responsive/node_modules/sharp
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "gulp-responsive"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.11.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.11.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /PROJECT_PATH/npm-debug.log
```

Currently using `node v0.12.7` and `npm 2.14.2` on Mac 10.10.5 Yosemite.

**Comment by rvboris** [comment]
Same problem io.js 1.6.4, npm 2.7.5 on Windows

**Comment by mahnunchik** [comment]
Hi @jhough10 @rvboris please follow installation documentation of [sharp](https://github.com/lovell/sharp) library http://sharp.dimens.io/en/stable/install/

Notify me if it does not solve your problem.

**Comment by jhough10** [comment]
@mahnunchik works like a champ now.

If using a Mac I ran the following command `brew install homebrew/science/vips --with-webp --with-graphicsmagick` and it resolved the issue with being able to install gulp-responsive.

**Comment by mahnunchik** [comment]
@jhough10 great! :fireworks:

**Comment by Camiloruro** [comment]
:+1:
